/**
 *
 * Autor: Figueroa Martinez Joel Francisco
 * Fecha creacion: 08/12/2022
 * Fecha modificacion: 13/12/2022
 * Descripcion: panel que contiene el juego
 *
 */
package view;

import entity.Ball;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class PanelGrafico extends javax.swing.JPanel implements Runnable {

    //declaracion de variables
    private boolean play;
    private ImageIcon fondo;
    private final ArrayList<Ball> balls = new ArrayList<>();

    /**
     * constructor
     */
    public PanelGrafico() {
        initComponents();
        play = true;
        this.setBounds(0, 0, 300, 300);
        this.setBackground(Color.MAGENTA);
        this.setSize(500, 300);

        createBalls(3);

        this.setFocusable(true);

    }

    /**
     * método para dibujar en el panel
     *
     * @param g
     */
    @Override
    public void paint(Graphics g) {

        Dimension tamanio = this.getSize();
        fondo = new ImageIcon(getClass().getResource("../img/background.jpg"));
        g.drawImage(fondo.getImage(), 0, 0, tamanio.width, tamanio.height, null);
        setOpaque(false);

        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        paintBalls(g2d);

        Thread hilo = new Thread(this);
        if (play) {
            hilo.start();
        } else {
            hilo.interrupt();
        }

        try {
            Thread.sleep(15);
        } catch (InterruptedException ex) {
            Logger.getLogger(PanelGrafico.class.getName()).log(Level.SEVERE, null, ex);
        }

        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * método que gestiona hilo
     */
    @Override
    public void run() {
        moveBalls(balls);
    }

    /**
     * método que crea una lista de pelotas con valores aleatorios
     *
     * @param numberBalls
     */
    private void createBalls(int numberBalls) {
        for (int j = 0; j < numberBalls; j++) {
            balls.add(new Ball(this, (int) (Math.random() * (this.getWidth() - 30)),
                    (int) (Math.random() * (this.getHeight() - 30)),
                    new Color((int) ((Math.random() * 255)), (int) (Math.random() * 255), (int) (Math.random() * 255))));
        }
    }

    /**
     * metodo que agrega las pelotas al panel
     *
     * @param g2d
     */
    private void paintBalls(Graphics2D g2d) {
        for (Ball ball : balls) {
            ball.paint(g2d);
        }
    }

    /**
     * metodo para mover las pelotas
     *
     * @param balls
     */
    private void moveBalls(ArrayList<Ball> balls) {
        for (int i = 0; i < balls.size(); i++) {
            for (int j = i + 1; j < balls.size(); j++) {
                balls.get(i).collision(balls.get(j));
            }
            balls.get(i).move();
        }
    }

    /**
     * método para pausar o poner en play el juego
     *
     * @param play
     */
    public void setPlay(boolean play) {
        this.play = play;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
