package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.MouseInputListener;

/**
 *
 * @author labingsw05
 */
public class PanelGrafico extends javax.swing.JPanel implements Runnable, KeyListener, MouseInputListener, MouseMotionListener {

    private int x = 20;
    private int y = 20;
    private int posX = 20;
    private int posY = 20;
    private int angulo =0;
    boolean aumentarX = true;
    boolean aumentarY = true;

    public PanelGrafico() {
        initComponents();
        
        this.addMouseListener(this);
        this.addMouseMotionListener(this);
        this.setBounds(10, 10, 300, 300);
        this.setBackground(Color.MAGENTA);
        this.setSize(300, 300);
        
        this.addKeyListener(this); //agregar escucha al panel con los teclados
        this.setFocusable(true);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setColor(Color.yellow);
        g2d.fillOval(posX, posY, 50, 50);
        g2d.setColor(Color.BLUE);
        g2d.drawOval(posX, posY, 50, 50);
        
        
        
//        Toolkit t = Toolkit.getDefaultToolkit();
//        Image img = t.getImage("resources/images/continuar.png");
//        g2d.rotate(angulo*Math.PI/180, x, y);
//        g2d.drawImage(img, x, y, this);


        Thread hilo = new Thread(this);
        hilo.start();
        try {
            Thread.sleep(15);
        } catch (InterruptedException ex) {
            Logger.getLogger(PanelGrafico.class.getName()).log(Level.SEVERE, null, ex);
        }

      repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {

//        if (x + 32 < this.getHeight() && aumentarX) {
//            x++;
//            System.out.println(x + "  " + aumentarX);
//            aumentarX = true;
//        } 
        if (y + 32 < this.getHeight() && aumentarX) {
            y=(y+1)%this.getHeight();
            System.out.println(y + "  " + aumentarX);
            aumentarY = true;
        } 
    }

    @Override
    public void keyTyped(KeyEvent ke) {
        
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        int codigo = ke.getExtendedKeyCode();
        
        if (codigo==ke.VK_UP) {
            System.out.println("flecha arriba");
            angulo=(angulo+90)%360;
        }
        
        
        if (codigo==ke.VK_DOWN) {
            System.out.println("flecha abajo");
           y=(y+5)%this.getHeight();
            
        }
        
        
        if (codigo==ke.VK_LEFT) {
            System.out.println("flecha izquierda");
            x-=5;
        }
        
        
        if (codigo==ke.VK_RIGHT) {
            System.out.println("flecha derecha");
            x+=5;
        }
        
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        
    }

    @Override
    public void mouseClicked(MouseEvent me) {
//        System.out.println("click");
        posX=me.getX();
        posY=me.getY();
    }

    @Override
    public void mousePressed(MouseEvent me) {
        
    }

    @Override
    public void mouseReleased(MouseEvent me) {
        
    }

    @Override
    public void mouseEntered(MouseEvent me) {
        
    }

    @Override
    public void mouseExited(MouseEvent me) {
        
    }

    @Override
    public void mouseDragged(MouseEvent me) {
        
        System.out.println("dragged");
        if((me.getX()>0 && me.getY()>=0)  && (me.getX()<=this.getWidth() && me.getY()>=this.getHeight()-100)){
            
        }
        
    }

    @Override
    public void mouseMoved(MouseEvent me) {
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
